# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
                ('ipd', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='files', to='main.UserNode'),
        ),
    ]
